name: ✨Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "Feature:"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true
